CREATE TABLE public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  type TEXT NOT NULL, -- 'image' or 'post'
  image_url TEXT, -- For type 'image'
  link_url TEXT, -- For type 'image'
  post_id UUID REFERENCES public.posts(id) ON DELETE SET NULL, -- For type 'post'
  display_location TEXT NOT NULL, -- e.g., 'nail-salons', 'nail-supply'
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active banners" ON public.banners FOR SELECT USING (is_active = TRUE);
CREATE POLICY "Admins can manage banners" ON public.banners FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');