CREATE TABLE public.licenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  license_type TEXT,
  name TEXT,
  location TEXT -- 'From' column
);

ALTER TABLE public.licenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view licenses" ON public.licenses FOR SELECT USING (true);
CREATE POLICY "Admins can manage licenses" ON public.licenses FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');