// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ppzkhbrduuirkvtinkxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwemtoYnJkdXVpcmt2dGlua3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjQyMzEsImV4cCI6MjA2ODcwMDIzMX0.0CS0tbN5Shrn1wMaAwiSjJGhEj1sabnb8sxA_JCi-P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);